name: OfflineCommands
version: ${project.version}
main: io.github.jochyoua.offlinecommands.OfflineCommands
api-version: 1.13
authors: [ Jochyoua, Phoenix616 ]
softdepend: [ PlaceHolderAPI ]
description: A plugin to execute commands when a player joins
website: https://jochyoua.github.io

commands:
  offlinecommands:
    description: "Lists or adds commands for users!"
    permission: "offlinecommands.use"
    default: false