blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/8q2KPPnm6U
    about: Discord server for extra support
  - name: Spigot
    url: https://www.spigotmc.org/conversations/add?to=Jochyoua
    about: Direct message me on spigot